import { Head } from '@inertiajs/react';
import { AlertTriangle, Clock3, FileCheck2, FileClock, Radio, ShieldCheck } from 'lucide-react';
import { SourceFreshnessBadge } from '@/Components/Ancillary';
import PageContentLayout from '@/Components/Common/PageContentLayout';
import DashboardLayout from '@/Components/Dashboard/DashboardLayout';
import ReadBacklogChart from '@/Components/Radiology/ReadBacklogChart';
import { useRadiologyReads } from '@/features/radiology/hooks';
import { radiologyReadsSchema, type RadiologyReads } from '@/features/radiology/schemas';

const STATE_STYLE = {
  normal: 'border-healthcare-success/40 bg-healthcare-success/10 text-healthcare-success dark:text-healthcare-success-dark',
  stale: 'border-healthcare-warning/40 bg-healthcare-warning/10 text-healthcare-warning dark:text-healthcare-warning-dark',
  degraded: 'border-healthcare-warning/40 bg-healthcare-warning/10 text-healthcare-warning dark:text-healthcare-warning-dark',
  source_error: 'border-healthcare-critical/40 bg-healthcare-critical/10 text-healthcare-critical dark:text-healthcare-critical-dark',
  missing_feed: 'border-healthcare-warning/40 bg-healthcare-warning/10 text-healthcare-warning dark:text-healthcare-warning-dark',
  no_data: 'border-healthcare-border bg-healthcare-background text-healthcare-text-secondary dark:border-healthcare-border-dark dark:bg-healthcare-background-dark dark:text-healthcare-text-secondary-dark',
} as const;

const URGENCY_STYLE = {
  normal: 'border-healthcare-success/40 text-healthcare-success dark:text-healthcare-success-dark',
  warning: 'border-healthcare-warning/40 text-healthcare-warning dark:text-healthcare-warning-dark',
  breach: 'border-healthcare-critical/40 text-healthcare-critical dark:text-healthcare-critical-dark',
  stale: 'border-healthcare-warning/40 text-healthcare-warning dark:text-healthcare-warning-dark',
  degraded: 'border-healthcare-warning/40 text-healthcare-warning dark:text-healthcare-warning-dark',
  unconfigured: 'border-healthcare-border text-healthcare-text-secondary dark:border-healthcare-border-dark dark:text-healthcare-text-secondary-dark',
} as const;

function duration(value: number | null) {
  if (value === null) return 'Unavailable';
  if (value < 60) return `${value.toLocaleString()} min`;
  return `${Math.floor(value / 60)}h ${value % 60}m`;
}

function StateCounts({ values }: { values: RadiologyReads['reportStates'] }) {
  return <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{values.map((value) => <div key={value.state} className="rounded-md border border-healthcare-border p-3 dark:border-healthcare-border-dark"><p className="text-xs uppercase tracking-wide text-healthcare-text-secondary dark:text-healthcare-text-secondary-dark">{value.state.replace('_', ' ')}</p><p className="mt-1 text-xl font-semibold tabular-nums text-healthcare-text-primary dark:text-healthcare-text-primary-dark">{value.count}</p></div>)}</div>;
}

export default function RadiologyReadsPage({ radiologyReads }: { radiologyReads: RadiologyReads }) {
  const initial = radiologyReadsSchema.parse(radiologyReads);
  const query = useRadiologyReads(initial);
  const view = query.data;
  const cards = [
    { label: 'Unread exams', value: view.unread.total.toLocaleString(), detail: `Oldest ${duration(view.unread.oldestAgeMinutes)}`, Icon: FileClock },
    { label: 'Open critical loops', value: view.criticalLoops.summary.open.toLocaleString(), detail: `Oldest ${duration(view.criticalLoops.summary.oldestOpenAgeMinutes)}`, Icon: Radio },
    { label: 'Prelim to final median', value: duration(view.preliminaryToFinal.medianMinutes), detail: `${view.preliminaryToFinal.count} comparable exams`, Icon: Clock3 },
    { label: 'Corrections', value: (view.reportStates.find((state) => state.state === 'corrected')?.count ?? 0).toLocaleString(), detail: 'Original final clock preserved', Icon: FileCheck2 },
  ];

  return (
    <DashboardLayout>
      <Head title="Reads and Results - Radiology" />
      <PageContentLayout title="Reads and Results" subtitle="Unread depth, report aging, corrections, and critical-result closed-loop health" headerContent={<SourceFreshnessBadge value={view.freshness} />}>
        <div className="space-y-4">
          <div role="status" className={`flex flex-wrap items-center justify-between gap-3 rounded-md border p-3 text-sm ${STATE_STYLE[view.state]}`}><span>{view.stateMessage}</span><span className="tabular-nums">Generated {new Date(view.generatedAt).toLocaleTimeString()}</span></div>

          <form action="/radiology/reads" method="get" aria-label="Radiology reads filters" className="grid gap-3 rounded-lg border border-healthcare-border bg-healthcare-surface p-4 dark:border-healthcare-border-dark dark:bg-healthcare-surface-dark sm:grid-cols-2 lg:grid-cols-6">
            <label className="text-sm text-healthcare-text-secondary dark:text-healthcare-text-secondary-dark">Report state<select name="state" defaultValue={view.filters.state} className="mt-1 w-full rounded-md border border-healthcare-border bg-healthcare-background px-3 py-2 text-healthcare-text-primary dark:border-healthcare-border-dark dark:bg-healthcare-background-dark dark:text-healthcare-text-primary-dark">{view.filterOptions.states.map((state) => <option key={state} value={state}>{state.replace('_', ' ')}</option>)}</select></label>
            <label className="text-sm text-healthcare-text-secondary dark:text-healthcare-text-secondary-dark">Priority<select name="priority" defaultValue={view.filters.priority ?? ''} className="mt-1 w-full rounded-md border border-healthcare-border bg-healthcare-background px-3 py-2 text-healthcare-text-primary dark:border-healthcare-border-dark dark:bg-healthcare-background-dark dark:text-healthcare-text-primary-dark"><option value="">All priorities</option>{view.filterOptions.priorities.map((priority) => <option key={priority} value={priority}>{priority}</option>)}</select></label>
            <label className="text-sm text-healthcare-text-secondary dark:text-healthcare-text-secondary-dark">Subspecialty<select name="subspecialty" defaultValue={view.filters.subspecialty ?? ''} className="mt-1 w-full rounded-md border border-healthcare-border bg-healthcare-background px-3 py-2 text-healthcare-text-primary dark:border-healthcare-border-dark dark:bg-healthcare-background-dark dark:text-healthcare-text-primary-dark"><option value="">All subspecialties</option>{view.filterOptions.subspecialties.map((item) => <option key={item.code} value={item.code}>{item.label}</option>)}</select></label>
            <label className="text-sm text-healthcare-text-secondary dark:text-healthcare-text-secondary-dark">Modality<select name="modality" defaultValue={view.filters.modality ?? ''} className="mt-1 w-full rounded-md border border-healthcare-border bg-healthcare-background px-3 py-2 text-healthcare-text-primary dark:border-healthcare-border-dark dark:bg-healthcare-background-dark dark:text-healthcare-text-primary-dark"><option value="">All modalities</option>{view.filterOptions.modalities.map((item) => <option key={item.code} value={item.code}>{item.label}</option>)}</select></label>
            <label className="text-sm text-healthcare-text-secondary dark:text-healthcare-text-secondary-dark">Window<select name="windowHours" defaultValue={view.filters.windowHours} className="mt-1 w-full rounded-md border border-healthcare-border bg-healthcare-background px-3 py-2 text-healthcare-text-primary dark:border-healthcare-border-dark dark:bg-healthcare-background-dark dark:text-healthcare-text-primary-dark">{view.filterOptions.windowHours.map((hours) => <option key={hours} value={hours}>{hours} hours</option>)}</select></label>
            <button type="submit" className="self-end rounded-md bg-healthcare-primary px-4 py-2 font-medium text-white hover:bg-healthcare-primary-hover dark:bg-healthcare-primary-dark">Apply</button>
          </form>

          <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{cards.map(({ label, value, detail, Icon }) => <section key={label} className="rounded-lg border border-healthcare-border bg-healthcare-surface p-4 dark:border-healthcare-border-dark dark:bg-healthcare-surface-dark"><div className="flex items-center justify-between gap-2"><p className="text-sm text-healthcare-text-secondary dark:text-healthcare-text-secondary-dark">{label}</p><Icon className="size-4 text-healthcare-primary" aria-hidden="true" /></div><p className="mt-2 text-2xl font-semibold tabular-nums text-healthcare-text-primary dark:text-healthcare-text-primary-dark">{value}</p><p className="mt-1 text-xs text-healthcare-text-secondary dark:text-healthcare-text-secondary-dark">{detail}</p></section>)}</div>

          <section className="rounded-lg border border-healthcare-border bg-healthcare-surface dark:border-healthcare-border-dark dark:bg-healthcare-surface-dark"><div className="border-b border-healthcare-border p-4 dark:border-healthcare-border-dark"><h2 className="font-semibold text-healthcare-text-primary dark:text-healthcare-text-primary-dark">Unread backlog growth</h2><p className="mt-1 text-sm text-healthcare-text-secondary dark:text-healthcare-text-secondary-dark">{view.backlog.definition}</p></div><ReadBacklogChart points={view.backlog.points} /></section>

          {(view.backlog.missing.completionTimestampCount > 0 || view.backlog.missing.finalTimestampCount > 0) ? <div role="alert" className="flex gap-3 rounded-md border border-healthcare-warning/40 bg-healthcare-warning/10 p-3 text-sm text-healthcare-warning dark:text-healthcare-warning-dark"><AlertTriangle className="mt-0.5 size-4 shrink-0" aria-hidden="true" /><span>Missing timestamps: {view.backlog.missing.completionTimestampCount} acquisition completion and {view.backlog.missing.finalTimestampCount} final report. These records are excluded from affected bucket calculations.</span></div> : null}

          <div className="grid gap-4 xl:grid-cols-2">
            <section className="rounded-lg border border-healthcare-border bg-healthcare-surface p-4 dark:border-healthcare-border-dark dark:bg-healthcare-surface-dark"><h2 className="font-semibold text-healthcare-text-primary dark:text-healthcare-text-primary-dark">Report-state and queue depth</h2><div className="mt-3"><StateCounts values={view.reportStates} /></div><div className="mt-4 grid gap-4 sm:grid-cols-2"><div><h3 className="text-sm font-medium text-healthcare-text-primary dark:text-healthcare-text-primary-dark">By priority</h3><ul className="mt-2 space-y-2">{view.unread.byPriority.map((row) => <li key={row.priority} className="flex justify-between gap-3 text-sm"><span className="capitalize text-healthcare-text-secondary dark:text-healthcare-text-secondary-dark">{row.priority}</span><span className="tabular-nums text-healthcare-text-primary dark:text-healthcare-text-primary-dark">{row.count} · oldest {duration(row.oldestAgeMinutes)}</span></li>)}</ul></div><div><h3 className="text-sm font-medium text-healthcare-text-primary dark:text-healthcare-text-primary-dark">By subspecialty</h3><ul className="mt-2 space-y-2">{view.unread.bySubspecialty.map((row) => <li key={row.code} className="flex justify-between gap-3 text-sm"><span className="text-healthcare-text-secondary dark:text-healthcare-text-secondary-dark">{row.label}</span><span className="tabular-nums text-healthcare-text-primary dark:text-healthcare-text-primary-dark">{row.count} · {duration(row.oldestAgeMinutes)}</span></li>)}</ul></div></div></section>
            <section className="rounded-lg border border-healthcare-border bg-healthcare-surface p-4 dark:border-healthcare-border-dark dark:bg-healthcare-surface-dark"><h2 className="font-semibold text-healthcare-text-primary dark:text-healthcare-text-primary-dark">Closed-loop critical results</h2><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-5">{view.criticalLoops.summary.byState.map((row) => <div key={row.state} className="rounded-md border border-healthcare-border p-2 text-center dark:border-healthcare-border-dark"><p className="text-xs text-healthcare-text-secondary dark:text-healthcare-text-secondary-dark">{row.state.replace('_', ' ')}</p><p className="mt-1 font-semibold tabular-nums text-healthcare-text-primary dark:text-healthcare-text-primary-dark">{row.count}</p></div>)}</div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-healthcare-text-secondary dark:text-healthcare-text-secondary-dark">Identified to notified</dt><dd className="font-medium text-healthcare-text-primary dark:text-healthcare-text-primary-dark">Median {duration(view.criticalLoops.timings.identifiedToNotified.medianMinutes)}</dd></div><div><dt className="text-healthcare-text-secondary dark:text-healthcare-text-secondary-dark">Notified to acknowledged</dt><dd className="font-medium text-healthcare-text-primary dark:text-healthcare-text-primary-dark">Median {duration(view.criticalLoops.timings.notifiedToAcknowledged.medianMinutes)}</dd></div></dl>{view.criticalLoops.openItems.length > 0 ? <ul className="mt-4 space-y-2">{view.criticalLoops.openItems.map((item) => <li key={item.criticalResultUuid}><a href={item.drillHref} className="flex justify-between gap-3 rounded-md border border-healthcare-border p-3 text-sm hover:border-healthcare-primary dark:border-healthcare-border-dark"><span><span className="font-medium text-healthcare-text-primary dark:text-healthcare-text-primary-dark">{item.findingClass}</span><span className="ml-2 text-healthcare-text-secondary dark:text-healthcare-text-secondary-dark">{item.modality ?? 'Unknown modality'} · {item.state.replace('_', ' ')}</span></span><span className="tabular-nums text-healthcare-critical dark:text-healthcare-critical-dark">{duration(item.ageMinutes)}</span></a></li>)}</ul> : <p className="mt-4 text-sm text-healthcare-success dark:text-healthcare-success-dark">No open critical-result loops match this filter.</p>}</section>
          </div>

          <section className="rounded-lg border border-healthcare-border bg-healthcare-surface p-4 dark:border-healthcare-border-dark dark:bg-healthcare-surface-dark"><div className="flex flex-wrap items-center justify-between gap-2"><div><h2 className="font-semibold text-healthcare-text-primary dark:text-healthcare-text-primary-dark">Read queue</h2><p className="mt-1 text-sm text-healthcare-text-secondary dark:text-healthcare-text-secondary-dark">Operational metadata only; clinical report narrative is not returned.</p></div><span className="flex items-center gap-1 text-xs text-healthcare-success dark:text-healthcare-success-dark"><ShieldCheck className="size-4" aria-hidden="true" />Report text excluded</span></div><div className="mt-3 overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="text-xs uppercase text-healthcare-text-secondary dark:text-healthcare-text-secondary-dark"><tr><th className="px-3 py-2">Exam</th><th className="px-3 py-2">Priority</th><th className="px-3 py-2">Report state</th><th className="px-3 py-2">Queue age</th><th className="px-3 py-2">SLA state</th><th className="px-3 py-2">Version</th></tr></thead><tbody>{view.items.map((item) => <tr key={item.examUuid} className="border-t border-healthcare-border dark:border-healthcare-border-dark"><td className="px-3 py-3"><a href={item.drillHref} className="font-medium text-healthcare-primary hover:underline">{item.label}</a><p className="text-xs text-healthcare-text-secondary dark:text-healthcare-text-secondary-dark">{item.modality ?? 'Unknown'} · {item.subspecialtyLabel ?? 'Unassigned'} · {item.patientRef}</p></td><td className="px-3 py-3 capitalize">{item.priority}</td><td className="px-3 py-3 capitalize">{item.reportState.replace('_', ' ')}{item.correctionCount > 0 ? ` · ${item.correctionCount} correction` : ''}</td><td className="px-3 py-3 tabular-nums">{duration(item.ageMinutes)}</td><td className="px-3 py-3"><span className={`rounded-md border px-2 py-1 text-xs font-medium ${URGENCY_STYLE[item.urgency]}`}>{item.urgency}</span></td><td className="px-3 py-3">{item.sourceReportVersion ?? '—'}</td></tr>)}{view.items.length === 0 ? <tr><td colSpan={6} className="px-3 py-8 text-center text-healthcare-text-secondary dark:text-healthcare-text-secondary-dark">No read-queue items match the selected filters.</td></tr> : null}</tbody></table></div></section>

          <details className="rounded-lg border border-healthcare-border bg-healthcare-surface p-4 text-sm dark:border-healthcare-border-dark dark:bg-healthcare-surface-dark"><summary className="cursor-pointer font-medium text-healthcare-text-primary dark:text-healthcare-text-primary-dark">Timing definitions and missing-data policy</summary><p className="mt-3 text-healthcare-text-secondary dark:text-healthcare-text-secondary-dark">{view.preliminaryToFinal.definition}</p><p className="mt-2 text-healthcare-text-secondary dark:text-healthcare-text-secondary-dark">Preliminary-to-final observations: {view.preliminaryToFinal.count}; missing preliminary: {view.preliminaryToFinal.missingPreliminaryCount}; excluded negative intervals: {view.preliminaryToFinal.excludedNegativeCount}; p90: {duration(view.preliminaryToFinal.p90Minutes)}; maximum: {duration(view.preliminaryToFinal.maxMinutes)}.</p><p className="mt-2 text-healthcare-text-secondary dark:text-healthcare-text-secondary-dark">{view.privacy.identifierPolicy}</p></details>
        </div>
      </PageContentLayout>
    </DashboardLayout>
  );
}
