#!/usr/bin/env python3
"""Generate tests/ci/shard-manifest.json from Q6 timing evidence (plan S1).

Consumes one or more release-evidence directories containing
backend-feature-*-release-evidence/phpunit-setup-split.ndjson (the per-test
records the Q6 instrumentation emits), computes per-test-file wall-time
medians across runs, and LPT-packs the files into FEATURE_SHARD_COUNT bins.

Weights come from rolling medians of clean runs per the §3.2.9 ordering gate:
the manifest must never be hand-tuned. Regenerate with:

    python3 scripts/ci/generate-shard-manifest.py /path/to/run1 /path/to/run2 ...

where each argument is a directory holding that run's downloaded
backend-feature-*-release-evidence artifacts.
"""

import json
import statistics
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

SHARD_COUNT = 8
REPO_ROOT = Path(__file__).resolve().parents[2]
MANIFEST_PATH = REPO_ROOT / "tests" / "ci" / "shard-manifest.json"
# Files excluded from the PHPUnit runner (see phpunit.xml). Empty since plan
# item D4 converted the last Pest-syntax files; kept for the next exclusion.
EXCLUDED: set[str] = set()


def discovered_feature_files() -> list[str]:
    files = sorted(
        str(p.relative_to(REPO_ROOT))
        for p in (REPO_ROOT / "tests" / "Feature").rglob("*Test.php")
    )
    return [f for f in files if f not in EXCLUDED]


def test_id_to_file(test_id: str) -> str | None:
    class_name = test_id.split("::", 1)[0]
    prefix = "Tests\\Feature\\"
    if not class_name.startswith(prefix):
        return None
    return "tests/Feature/" + class_name[len(prefix):].replace("\\", "/") + ".php"


def collect_run_totals(run_dir: Path) -> dict[str, float]:
    totals: dict[str, float] = defaultdict(float)
    ndjson_files = sorted(run_dir.glob("**/phpunit-setup-split.ndjson"))
    if not ndjson_files:
        raise SystemExit(f"No phpunit-setup-split.ndjson under {run_dir}")
    for ndjson in ndjson_files:
        with ndjson.open() as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                record = json.loads(line)
                file = test_id_to_file(record["test"])
                if file is not None:
                    totals[file] += float(record["total_s"])
    return dict(totals)


def main(run_dirs: list[str]) -> None:
    if len(run_dirs) < 3:
        raise SystemExit("Need at least 3 run directories (§3.2.9: rolling medians of 3 clean runs)")

    runs = [collect_run_totals(Path(d)) for d in run_dirs]
    files = discovered_feature_files()

    weights: dict[str, float] = {}
    unmeasured: list[str] = []
    for file in files:
        samples = [run[file] for run in runs if file in run]
        if samples:
            weights[file] = round(statistics.median(samples), 3)
        else:
            unmeasured.append(file)

    # Deterministic default for files with no measurement in any run: the
    # median measured file weight (typical file), never zero.
    default_weight = round(statistics.median(weights.values()), 3)
    for file in unmeasured:
        weights[file] = default_weight

    # LPT: heaviest first into the least-loaded bin; ties break on lowest
    # bin index, then lexicographic file order, so output is deterministic.
    bins = [0.0] * SHARD_COUNT
    assignments: dict[str, int] = {}
    for file in sorted(files, key=lambda f: (-weights[f], f)):
        shard = min(range(SHARD_COUNT), key=lambda i: (bins[i], i))
        assignments[file] = shard
        bins[shard] += weights[file]

    git_head = subprocess.run(
        ["git", "-C", str(REPO_ROOT), "rev-parse", "--short", "HEAD"],
        capture_output=True, text=True, check=True,
    ).stdout.strip()

    manifest = {
        "_comment": "Generated by scripts/ci/generate-shard-manifest.py — do not hand-edit. "
                    "Weights are per-file medians (seconds) from Q6 phpunit-setup-split.ndjson evidence.",
        "generated_at_commit": git_head,
        "source_runs": [Path(d).name for d in run_dirs],
        "shard_count": SHARD_COUNT,
        "default_weight_s": default_weight,
        "shard_load_s": {str(i): round(bins[i], 3) for i in range(SHARD_COUNT)},
        "assignments": {f: {"shard": assignments[f], "weight_s": weights[f]} for f in sorted(files)},
    }

    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST_PATH.write_text(json.dumps(manifest, indent=2) + "\n")

    print(f"Wrote {MANIFEST_PATH.relative_to(REPO_ROOT)}")
    print(f"  files: {len(files)} ({len(unmeasured)} unmeasured -> default {default_weight}s)")
    for i in range(SHARD_COUNT):
        count = sum(1 for s in assignments.values() if s == i)
        print(f"  shard {i}: {bins[i]:8.1f}s across {count} files")


if __name__ == "__main__":
    main(sys.argv[1:])
