<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        if (DB::getDriverName() !== 'pgsql') {
            return;
        }

        DB::unprepared(<<<'SQL'
            CREATE SCHEMA IF NOT EXISTS audit;

            CREATE TABLE IF NOT EXISTS audit.user_events (
                event_cursor bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                event_uuid uuid NOT NULL UNIQUE,
                occurred_at timestamptz NOT NULL,
                recorded_at timestamptz NOT NULL DEFAULT now(),
                actor_user_id bigint,
                actor_username varchar(190),
                actor_role varchar(80),
                principal_ref char(64),
                session_ref char(64),
                action varchar(120) NOT NULL,
                category varchar(40) NOT NULL,
                outcome varchar(40) NOT NULL,
                reason varchar(120),
                auth_method varchar(40),
                source_surface varchar(40) NOT NULL,
                target_type varchar(80),
                target_id varchar(190),
                route_name varchar(190),
                uri_template varchar(500),
                http_method varchar(10),
                http_status smallint,
                request_uuid uuid NOT NULL,
                client_ip inet,
                user_agent varchar(512),
                changes jsonb NOT NULL DEFAULT '{}'::jsonb,
                metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
                schema_version smallint NOT NULL DEFAULT 1,
                CONSTRAINT user_events_action_namespaced CHECK (
                    action ~ '^[a-z][a-z0-9_-]*(\.[a-z0-9_-]+)+$'
                ),
                CONSTRAINT user_events_http_method_check CHECK (
                    http_method IS NULL OR http_method IN ('GET', 'HEAD', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS')
                ),
                CONSTRAINT user_events_http_status_check CHECK (
                    http_status IS NULL OR http_status BETWEEN 100 AND 599
                ),
                CONSTRAINT user_events_schema_version_check CHECK (schema_version > 0)
            );

            CREATE INDEX IF NOT EXISTS user_events_occurred_cursor_idx
                ON audit.user_events (occurred_at DESC, event_cursor DESC);
            CREATE INDEX IF NOT EXISTS user_events_actor_occurred_idx
                ON audit.user_events (actor_user_id, occurred_at DESC)
                WHERE actor_user_id IS NOT NULL;
            CREATE INDEX IF NOT EXISTS user_events_action_occurred_idx
                ON audit.user_events (action, occurred_at DESC);
            CREATE INDEX IF NOT EXISTS user_events_category_outcome_idx
                ON audit.user_events (category, outcome, occurred_at DESC);
            CREATE INDEX IF NOT EXISTS user_events_auth_method_idx
                ON audit.user_events (auth_method, occurred_at DESC)
                WHERE auth_method IS NOT NULL;
            CREATE INDEX IF NOT EXISTS user_events_target_idx
                ON audit.user_events (target_type, target_id, occurred_at DESC)
                WHERE target_type IS NOT NULL;
            CREATE INDEX IF NOT EXISTS user_events_request_uuid_idx
                ON audit.user_events (request_uuid);
            CREATE INDEX IF NOT EXISTS user_events_principal_ref_idx
                ON audit.user_events (principal_ref, occurred_at DESC)
                WHERE principal_ref IS NOT NULL;

            CREATE OR REPLACE FUNCTION audit.reject_user_event_mutation()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'audit.user_events is append-only';
            END;
            $$ LANGUAGE plpgsql;

            DROP TRIGGER IF EXISTS user_events_append_only ON audit.user_events;
            CREATE TRIGGER user_events_append_only
            BEFORE UPDATE OR DELETE ON audit.user_events
            FOR EACH ROW EXECUTE FUNCTION audit.reject_user_event_mutation();
            SQL);
    }

    public function down(): void
    {
        if (DB::getDriverName() !== 'pgsql') {
            return;
        }

        DB::unprepared(<<<'SQL'
            DROP TRIGGER IF EXISTS user_events_append_only ON audit.user_events;
            DROP TABLE IF EXISTS audit.user_events;
            DROP FUNCTION IF EXISTS audit.reject_user_event_mutation();
            SQL);
    }
};
