<?php

declare(strict_types=1);

use Illuminate\Contracts\Console\Kernel;
use Illuminate\Routing\Route as IlluminateRoute;
use Illuminate\Support\Facades\Route;

require dirname(__DIR__).'/vendor/autoload.php';

/**
 * Generate the mobile route inventory (plan §4.2) deterministically from the
 * live Laravel route table, so the snapshot cannot silently drift. The
 * authoritative route↔OpenAPI parity guard remains tests/Feature/MobileBffTest.php;
 * this document is a human-readable, CI-freshness-checked mirror of the live
 * `/api/mobile/v1/*` surface. Emits no dates or volatile counts.
 */
const OUTPUT = 'docs/hummingbird/api-contract/mobile-route-contract-inventory.md';
const PREFIX = 'api/mobile/v1/';

$root = dirname(__DIR__);

$app = require $root.'/bootstrap/app.php';
$app->make(Kernel::class)->bootstrap();

$operations = [];
foreach (Route::getRoutes() as $route) {
    if (! $route instanceof IlluminateRoute || ! str_starts_with($route->uri(), PREFIX)) {
        continue;
    }
    foreach ($route->methods() as $method) {
        if (in_array($method, ['HEAD', 'OPTIONS'], true)) {
            continue;
        }
        $operations[] = $method.' /'.$route->uri();
    }
}
$operations = array_values(array_unique($operations));
sort($operations);

$rows = '';
foreach ($operations as $operation) {
    [$method, $path] = explode(' ', $operation, 2);
    $rows .= "| {$method} | `{$path}` |\n";
}

$count = count($operations);
$rendered = <<<MD
<!-- Generated by scripts/generate-hummingbird-route-inventory.php. Do not edit by hand. -->

# Mobile Route / OpenAPI Contract Inventory

**Scope:** `/api/mobile/v1/*` Laravel routes compared with
[`hummingbird-bff.v1.yaml`](hummingbird-bff.v1.yaml).

This is a generated, CI-freshness-checked snapshot of the live route surface. The
authoritative route↔OpenAPI parity guard is
`tests/Feature/MobileBffTest.php::test_laravel_mobile_routes_match_the_openapi_contract_inventory`;
the patient-communications operations are additionally enforced by
`scripts/verify-hummingbird-staff-contract.php`. This file carries no date or test
counts so `--check` stays byte-stable.

## Verification commands

```bash
php scripts/generate-hummingbird-route-inventory.php --check
php artisan test --filter=MobileBffTest
php scripts/verify-hummingbird-staff-contract.php
```

## Live routes ({$count})

| Method | Path |
| ------ | ---- |
{$rows}
MD;

$outputPath = $root.'/'.OUTPUT;

if (in_array('--check', $argv, true)) {
    $current = is_file($outputPath) ? file_get_contents($outputPath) : false;
    if ($current !== $rendered) {
        fwrite(STDERR, OUTPUT." is stale. Run: php scripts/generate-hummingbird-route-inventory.php\n");
        exit(1);
    }
    fwrite(STDOUT, OUTPUT." is current.\n");
    exit(0);
}

file_put_contents($outputPath, $rendered);
fwrite(STDOUT, 'Generated '.OUTPUT." ({$count} routes).\n");
