<?php

declare(strict_types=1);

use Symfony\Component\Yaml\Yaml;

require dirname(__DIR__).'/vendor/autoload.php';

const LEDGER = 'docs/hummingbird/capability-ledger.v1.yaml';
const OUTPUT = 'docs/hummingbird/generated/capability-coverage.md';

/** @param list<string> $values */
function cells(array $values): string
{
    if ($values === []) {
        return '—';
    }

    return implode('<br>', array_map(
        static fn (string $value): string => '`'.str_replace('|', '\|', $value).'`',
        $values,
    ));
}

/** @param array<string, int> $counts */
function countSummary(array $counts): string
{
    ksort($counts);

    return implode(', ', array_map(
        static fn (string $key, int $count): string => "`{$key}` {$count}",
        array_keys($counts),
        array_values($counts),
    ));
}

$root = dirname(__DIR__);
$ledger = Yaml::parseFile($root.'/'.LEDGER);
$capabilities = $ledger['capabilities'] ?? [];

if (! is_array($capabilities) || ! array_is_list($capabilities)) {
    fwrite(STDERR, LEDGER." has no capability list.\n");
    exit(1);
}

usort($capabilities, static fn (array $left, array $right): int => [$left['domain'], $left['id']] <=> [$right['domain'], $right['id']]);

$statusCounts = [];
$dispositionCounts = [];
$webRouteCount = 0;
$staffOperationCount = 0;
$patientOperationCount = 0;
$unresolved = [];

foreach ($capabilities as $capability) {
    $status = (string) $capability['implementation_status'];
    $disposition = (string) $capability['target_disposition'];
    $statusCounts[$status] = ($statusCounts[$status] ?? 0) + 1;
    $dispositionCounts[$disposition] = ($dispositionCounts[$disposition] ?? 0) + 1;
    $webRouteCount += count($capability['web_routes']);
    $staffOperationCount += count($capability['staff_bff_operations']);
    $patientOperationCount += count($capability['patient_api_operations'] ?? []);
    if ($status !== 'complete') {
        $unresolved[] = $capability;
    }
}

$lines = [
    '<!-- Generated by scripts/generate-hummingbird-capability-report.php. Do not edit by hand. -->',
    '',
    '# Hummingbird capability coverage',
    '',
    '> Source: `'.LEDGER.'`',
    '> Ledger date: '.($ledger['as_of'] ?? 'unknown'),
    '> **Counts are inventory controls, not a functional-parity percentage.** A capability is complete only when its evidence satisfies the dated execution plan.',
    '',
    '## Inventory summary',
    '',
    '- Capabilities: '.count($capabilities),
    '- Navigation routes with a single ledger owner: '.$webRouteCount,
    '- Staff mobile/auth operations with a single ledger owner: '.$staffOperationCount,
    '- Patient API operations with a single ledger owner: '.$patientOperationCount,
    '- Implementation states: '.countSummary($statusCounts),
    '- Target dispositions: '.countSummary($dispositionCounts),
    '',
    '## Capability ledger',
    '',
    '| Domain | Capability | Status | Target | Phase | Product owner | Engineering owner | Web routes | Staff BFF operations | Patient API operations | iOS | Android |',
    '| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |',
];

foreach ($capabilities as $capability) {
    $lines[] = '| '.implode(' | ', [
        '`'.$capability['domain'].'`',
        '`'.$capability['id'].'` — '.$capability['title'],
        '`'.$capability['implementation_status'].'`',
        '`'.$capability['target_disposition'].'`',
        '`'.$capability['phase'].'`',
        $capability['owners']['product'],
        $capability['owners']['engineering'],
        cells($capability['web_routes']),
        cells($capability['staff_bff_operations']),
        cells($capability['patient_api_operations'] ?? []),
        cells($capability['ios_routes']),
        cells($capability['android_routes']),
    ]).' |';
}

$lines[] = '';
$lines[] = '## Unresolved implementation states';
$lines[] = '';
$lines[] = 'These are execution records, not inferred defects. Product and engineering owners must attach verification evidence before changing an item to `complete`.';
$lines[] = '';
$lines[] = '| Capability | Current state | Target | Phase |';
$lines[] = '| --- | --- | --- | --- |';
foreach ($unresolved as $capability) {
    $lines[] = "| `{$capability['id']}` | `{$capability['implementation_status']}` | `{$capability['target_disposition']}` | `{$capability['phase']}` |";
}
$lines[] = '';

$rendered = implode("\n", $lines);
$outputPath = $root.'/'.OUTPUT;

if (in_array('--check', $argv, true)) {
    $current = is_file($outputPath) ? file_get_contents($outputPath) : false;
    if ($current !== $rendered) {
        fwrite(STDERR, OUTPUT." is stale. Run: php scripts/generate-hummingbird-capability-report.php\n");
        exit(1);
    }

    fwrite(STDOUT, OUTPUT." is current.\n");
    exit(0);
}

if (! is_dir(dirname($outputPath)) && ! mkdir(dirname($outputPath), 0775, true) && ! is_dir(dirname($outputPath))) {
    fwrite(STDERR, 'Unable to create '.dirname(OUTPUT).".\n");
    exit(1);
}

file_put_contents($outputPath, $rendered);
fwrite(STDOUT, 'Generated '.OUTPUT.".\n");
