<?php

/**
 * Hospital 1 — Summit Regional Medical Center (HOSP1)
 *
 * SINGLE SOURCE OF TRUTH for the synthetic hospital. Generated from the Phase-1
 * VERIFIED Atlantic Health distributions (config/hospital/hospital-1-distributions.json,
 * workflow wf_b74378f9-d9b, 0 refuted / 39 checks). Access via App\\Support\\Hospital\\HospitalManifest.
 *
 * NOTE: facility.cad_facility_code ('ZEPHYRUS-500') is the IMMUTABLE join key across
 * model_catalog.json -> location_index.json -> FacilitySpaceLocationResolver/RTDC. Do NOT rename it;
 * Summit/HOSP1 branding is overlaid via facility.code / facility.name and the display layer.
 */

return [
    'facility' => [
        'code' => 'HOSP1',
        'name' => 'Summit Regional Medical Center',
        'short_name' => 'Summit Regional',
        'city' => 'Summit',
        'state' => 'PA',
        'region' => 'Mid-Atlantic',
        'type' => 'Level I Trauma Academic Medical Center',
        'licensed_beds' => 500,
        'cad_facility_code' => 'ZEPHYRUS-500',
        'tagline' => 'Operations Bridge',
    ],
    // Summit Health System network — the multi-facility filter dimension used by Process
    // Analysis / OR-Utilization surfaces. Replaces the real "Virtua *" hospital names.
    // Index 0 is the flagship we fully model (HOSP1); the rest are affiliate stubs.
    'network_facilities' => [
        ['name' => 'Summit Regional Medical Center', 'code' => 'HOSP1', 'role' => 'flagship'],
        ['name' => 'Summit Health — Hawthorne Campus', 'code' => 'HAWTH', 'role' => 'affiliate'],
        ['name' => 'Summit Health — Riverton Community Hospital', 'code' => 'RIVCH', 'role' => 'affiliate'],
        ['name' => 'Summit Health — Glenmoore Medical Center', 'code' => 'GLNMC', 'role' => 'affiliate'],
        ['name' => 'Summit Health — Castleton General Hospital', 'code' => 'CASTG', 'role' => 'affiliate'],
    ],
    'service_lines' => [
        [
            'code' => 'critical_care',
            'name' => 'Critical Care',
        ],
        [
            'code' => 'cardiology',
            'name' => 'Cardiology',
        ],
        [
            'code' => 'cardiovascular',
            'name' => 'Cardiovascular Surgery',
        ],
        [
            'code' => 'trauma_surgery',
            'name' => 'Trauma & General Surgery',
        ],
        [
            'code' => 'neurosciences',
            'name' => 'Neurosciences & Stroke',
        ],
        [
            'code' => 'medicine',
            'name' => 'Hospital Medicine',
        ],
        [
            'code' => 'adult_med_surg',
            'name' => 'Medical / Surgical',
        ],
        [
            'code' => 'oncology',
            'name' => 'Oncology & Hematology',
        ],
        [
            'code' => 'womens_health',
            'name' => 'Women\'s Health & Obstetrics',
        ],
        [
            'code' => 'pediatrics',
            'name' => 'Pediatrics',
        ],
        [
            'code' => 'neonatology',
            'name' => 'Neonatology',
        ],
        [
            'code' => 'behavioral_health',
            'name' => 'Behavioral Health',
        ],
        [
            'code' => 'rehabilitation',
            'name' => 'Physical Medicine & Rehabilitation',
        ],
        [
            'code' => 'emergency',
            'name' => 'Emergency Medicine',
        ],
        [
            'code' => 'burn',
            'name' => 'Burn & Reconstructive',
        ],
        [
            'code' => 'perioperative',
            'name' => 'Perioperative & Procedural',
        ],
    ],
    'units' => [
        [
            'abbr' => 'MICU',
            'cad_code' => 'MICU3',
            'name' => '3 West — Medical ICU (MICU)',
            'short_name' => 'Medical ICU',
            'floor' => 3,
            'service_line' => 'critical_care',
            'acuity' => 'icu',
            'type' => 'icu',
            'staffed_bed_count' => 24,
            'nurse_ratio' => 2.0,
            'atlantic_careunit' => 'MOBILE INTENSIVE CARE UNIT',
            'inpatient' => true,
        ],
        [
            'abbr' => 'SICU',
            'cad_code' => 'SICU3',
            'name' => '3 East — Surgical/Trauma ICU (SICU)',
            'short_name' => 'Surgical/Trauma ICU',
            'floor' => 3,
            'service_line' => 'trauma_surgery',
            'acuity' => 'icu',
            'type' => 'icu',
            'staffed_bed_count' => 24,
            'nurse_ratio' => 2.0,
            'atlantic_careunit' => 'MOBILE INTENSIVE CARE UNIT',
            'inpatient' => true,
        ],
        [
            'abbr' => 'NSICU',
            'cad_code' => 'NSICU3',
            'name' => '3 South — Neuroscience ICU (NSICU)',
            'short_name' => 'Neuroscience ICU',
            'floor' => 3,
            'service_line' => 'neurosciences',
            'acuity' => 'icu',
            'type' => 'icu',
            'staffed_bed_count' => 20,
            'nurse_ratio' => 2.0,
            'atlantic_careunit' => 'MOBILE INTENSIVE CARE UNIT',
            'inpatient' => true,
        ],
        [
            'abbr' => 'CVICU',
            'cad_code' => 'CVICU3',
            'name' => '3 North — Cardiovascular ICU (CVICU)',
            'short_name' => 'Cardiovascular ICU',
            'floor' => 3,
            'service_line' => 'cardiovascular',
            'acuity' => 'icu',
            'type' => 'icu',
            'staffed_bed_count' => 20,
            'nurse_ratio' => 2.0,
            'atlantic_careunit' => 'MOBILE INTENSIVE CARE UNIT',
            'inpatient' => true,
        ],
        [
            'abbr' => 'BURN',
            'cad_code' => 'BURN3',
            'name' => '3 Central — Burn ICU',
            'short_name' => 'Burn ICU',
            'floor' => 3,
            'service_line' => 'burn',
            'acuity' => 'burn_icu',
            'type' => 'icu',
            'staffed_bed_count' => 8,
            'nurse_ratio' => 2.0,
            'atlantic_careunit' => 'MOBILE INTENSIVE CARE UNIT',
            'inpatient' => true,
        ],
        [
            'abbr' => 'BHU',
            'cad_code' => 'BHU2',
            'name' => '2 — Inpatient Behavioral Health (Secure)',
            'short_name' => 'Inpatient Behavioral Health',
            'floor' => 2,
            'service_line' => 'behavioral_health',
            'acuity' => 'behavioral',
            'type' => 'med_surg',
            'staffed_bed_count' => 24,
            'nurse_ratio' => 6.0,
            'atlantic_careunit' => 'INPATIENT PSYCH',
            'inpatient' => true,
        ],
        [
            'abbr' => '4W',
            'cad_code' => 'MS4A',
            'name' => '4 West — Medical/Surgical',
            'short_name' => 'Adult Med/Surg A',
            'floor' => 4,
            'service_line' => 'adult_med_surg',
            'acuity' => 'med_surg',
            'type' => 'med_surg',
            'staffed_bed_count' => 28,
            'nurse_ratio' => 5.0,
            'atlantic_careunit' => 'INPATIENT',
            'inpatient' => true,
        ],
        [
            'abbr' => '4E',
            'cad_code' => 'MS4B',
            'name' => '4 East — Medical/Surgical',
            'short_name' => 'Adult Med/Surg B',
            'floor' => 4,
            'service_line' => 'adult_med_surg',
            'acuity' => 'med_surg',
            'type' => 'med_surg',
            'staffed_bed_count' => 28,
            'nurse_ratio' => 5.0,
            'atlantic_careunit' => 'INPATIENT',
            'inpatient' => true,
        ],
        [
            'abbr' => '5W',
            'cad_code' => 'MS5A',
            'name' => '5 West — Medical/Surgical',
            'short_name' => 'Adult Med/Surg C',
            'floor' => 5,
            'service_line' => 'adult_med_surg',
            'acuity' => 'med_surg',
            'type' => 'med_surg',
            'staffed_bed_count' => 28,
            'nurse_ratio' => 5.0,
            'atlantic_careunit' => 'INPATIENT',
            'inpatient' => true,
        ],
        [
            'abbr' => '5E',
            'cad_code' => 'MS5B',
            'name' => '5 East — Medical/Surgical',
            'short_name' => 'Adult Med/Surg D',
            'floor' => 5,
            'service_line' => 'adult_med_surg',
            'acuity' => 'med_surg',
            'type' => 'med_surg',
            'staffed_bed_count' => 28,
            'nurse_ratio' => 5.0,
            'atlantic_careunit' => 'INPATIENT',
            'inpatient' => true,
        ],
        [
            'abbr' => '6W',
            'cad_code' => 'MS6A',
            'name' => '6 West — Medical/Surgical',
            'short_name' => 'Adult Med/Surg E',
            'floor' => 6,
            'service_line' => 'adult_med_surg',
            'acuity' => 'med_surg',
            'type' => 'med_surg',
            'staffed_bed_count' => 24,
            'nurse_ratio' => 5.0,
            'atlantic_careunit' => 'INPATIENT',
            'inpatient' => true,
        ],
        [
            'abbr' => '6E',
            'cad_code' => 'MS6B',
            'name' => '6 East — Medical/Surgical',
            'short_name' => 'Adult Med/Surg F',
            'floor' => 6,
            'service_line' => 'adult_med_surg',
            'acuity' => 'med_surg',
            'type' => 'med_surg',
            'staffed_bed_count' => 24,
            'nurse_ratio' => 5.0,
            'atlantic_careunit' => 'INPATIENT',
            'inpatient' => true,
        ],
        [
            'abbr' => '7E',
            'cad_code' => 'TEL7A',
            'name' => '7 East — Telemetry & Cardiology',
            'short_name' => 'Adult Telemetry A',
            'floor' => 7,
            'service_line' => 'cardiology',
            'acuity' => 'telemetry',
            'type' => 'step_down',
            'staffed_bed_count' => 32,
            'nurse_ratio' => 4.0,
            'atlantic_careunit' => 'INPATIENT',
            'inpatient' => true,
        ],
        [
            'abbr' => '7W',
            'cad_code' => 'TEL7B',
            'name' => '7 West — Telemetry & Stepdown',
            'short_name' => 'Adult Telemetry B',
            'floor' => 7,
            'service_line' => 'medicine',
            'acuity' => 'telemetry',
            'type' => 'step_down',
            'staffed_bed_count' => 32,
            'nurse_ratio' => 4.0,
            'atlantic_careunit' => 'OBSERVATION',
            'inpatient' => true,
        ],
        [
            'abbr' => 'ANT',
            'cad_code' => 'ANT8',
            'name' => '8 — Antepartum (High-Risk OB)',
            'short_name' => 'Antepartum High-Risk OB',
            'floor' => 8,
            'service_line' => 'womens_health',
            'acuity' => 'women',
            'type' => 'med_surg',
            'staffed_bed_count' => 12,
            'nurse_ratio' => 4.0,
            'atlantic_careunit' => 'INPATIENT',
            'inpatient' => true,
        ],
        [
            'abbr' => 'PP',
            'cad_code' => 'PP8',
            'name' => '8 — Postpartum / Mother-Baby',
            'short_name' => 'Postpartum / Mother Baby',
            'floor' => 8,
            'service_line' => 'womens_health',
            'acuity' => 'women',
            'type' => 'med_surg',
            'staffed_bed_count' => 28,
            'nurse_ratio' => 4.0,
            'atlantic_careunit' => 'INPATIENT',
            'inpatient' => true,
        ],
        [
            'abbr' => 'GYN',
            'cad_code' => 'GYN8',
            'name' => '8 — Gynecology Surgery',
            'short_name' => 'Gynecology Surgery',
            'floor' => 8,
            'service_line' => 'womens_health',
            'acuity' => 'women',
            'type' => 'med_surg',
            'staffed_bed_count' => 8,
            'nurse_ratio' => 4.0,
            'atlantic_careunit' => 'INPATIENT',
            'inpatient' => true,
        ],
        [
            'abbr' => 'PED',
            'cad_code' => 'PED9',
            'name' => '9 — Pediatric Acute Care',
            'short_name' => 'Pediatric Acute Care',
            'floor' => 9,
            'service_line' => 'pediatrics',
            'acuity' => 'pediatrics',
            'type' => 'med_surg',
            'staffed_bed_count' => 24,
            'nurse_ratio' => 4.0,
            'atlantic_careunit' => 'INPATIENT',
            'inpatient' => true,
        ],
        [
            'abbr' => 'PICU',
            'cad_code' => 'PICU9',
            'name' => '9 — Pediatric ICU (PICU)',
            'short_name' => 'Pediatric ICU',
            'floor' => 9,
            'service_line' => 'pediatrics',
            'acuity' => 'pediatrics',
            'type' => 'med_surg',
            'staffed_bed_count' => 12,
            'nurse_ratio' => 4.0,
            'atlantic_careunit' => 'MOBILE INTENSIVE CARE UNIT',
            'inpatient' => true,
        ],
        [
            'abbr' => 'NICU',
            'cad_code' => 'NICU9',
            'name' => '9 — Neonatal ICU (NICU)',
            'short_name' => 'Neonatal ICU',
            'floor' => 9,
            'service_line' => 'neonatology',
            'acuity' => 'pediatrics',
            'type' => 'med_surg',
            'staffed_bed_count' => 12,
            'nurse_ratio' => 4.0,
            'atlantic_careunit' => 'NEWBORN',
            'inpatient' => true,
        ],
        [
            'abbr' => 'ONC',
            'cad_code' => 'ONC10',
            'name' => '10 — Oncology / Hematology',
            'short_name' => 'Oncology / Hematology',
            'floor' => 10,
            'service_line' => 'oncology',
            'acuity' => 'oncology',
            'type' => 'med_surg',
            'staffed_bed_count' => 24,
            'nurse_ratio' => 4.0,
            'atlantic_careunit' => 'INPATIENT',
            'inpatient' => true,
        ],
        [
            'abbr' => 'BMT',
            'cad_code' => 'BMT10',
            'name' => '10 — Bone Marrow Transplant / Cellular Therapy',
            'short_name' => 'Bone Marrow Transplant / Cellular Therapy',
            'floor' => 10,
            'service_line' => 'oncology',
            'acuity' => 'oncology',
            'type' => 'med_surg',
            'staffed_bed_count' => 16,
            'nurse_ratio' => 4.0,
            'atlantic_careunit' => 'INPATIENT',
            'inpatient' => true,
        ],
        [
            'abbr' => 'AIR',
            'cad_code' => 'AIR11',
            'name' => '11 — Acute Inpatient Rehabilitation',
            'short_name' => 'Acute Inpatient Rehabilitation',
            'floor' => 11,
            'service_line' => 'rehabilitation',
            'acuity' => 'rehab',
            'type' => 'med_surg',
            'staffed_bed_count' => 20,
            'nurse_ratio' => 6.0,
            'atlantic_careunit' => 'INPATIENT REHAB',
            'inpatient' => true,
        ],
        [
            'abbr' => 'ED',
            'cad_code' => 'ED',
            'name' => '1 — Emergency Department',
            'short_name' => 'Emergency Department',
            'floor' => 1,
            'service_line' => 'emergency',
            'acuity' => 'emergency',
            'type' => 'ed',
            'staffed_bed_count' => 148,
            'nurse_ratio' => 4.0,
            'atlantic_careunit' => 'EMERGENCY',
            'inpatient' => false,
        ],
        [
            'abbr' => 'OR',
            'cad_code' => 'PERIOP',
            'name' => '2 — Perioperative / Procedural Platform',
            'short_name' => 'Procedural Platform',
            'floor' => 2,
            'service_line' => 'perioperative',
            'acuity' => 'procedural',
            'type' => 'periop',
            'staffed_bed_count' => 44,
            'nurse_ratio' => null,
            'atlantic_careunit' => 'HOSPITAL OUTPATIENT SURGERY',
            'inpatient' => false,
        ],
    ],
    'providers' => [
        [
            'name' => 'Dr. Anita Raghunathan',
            'specialty' => 'critical_care',
            'role' => 'intensivist',
            'npi' => '1700000001',
        ],
        [
            'name' => 'Dr. Marcus Ellison',
            'specialty' => 'critical_care',
            'role' => 'intensivist',
            'npi' => '1700000002',
        ],
        [
            'name' => 'Dr. Priya Venkataraman',
            'specialty' => 'cardiology',
            'role' => 'attending',
            'npi' => '1700000003',
        ],
        [
            'name' => 'Dr. Daniel Brevik',
            'specialty' => 'cardiology',
            'role' => 'attending',
            'npi' => '1700000004',
        ],
        [
            'name' => 'Dr. Sofia Marchetti',
            'specialty' => 'cardiovascular',
            'role' => 'surgeon',
            'npi' => '1700000005',
        ],
        [
            'name' => 'Dr. James Okonkwo',
            'specialty' => 'trauma_surgery',
            'role' => 'surgeon',
            'npi' => '1700000006',
        ],
        [
            'name' => 'Dr. Hannah Wexler',
            'specialty' => 'trauma_surgery',
            'role' => 'surgeon',
            'npi' => '1700000007',
        ],
        [
            'name' => 'Dr. Rahul Desai',
            'specialty' => 'neurosciences',
            'role' => 'attending',
            'npi' => '1700000008',
        ],
        [
            'name' => 'Dr. Eleanor Pruitt',
            'specialty' => 'neurosciences',
            'role' => 'attending',
            'npi' => '1700000009',
        ],
        [
            'name' => 'Dr. Thomas Achebe',
            'specialty' => 'medicine',
            'role' => 'hospitalist',
            'npi' => '1700000010',
        ],
        [
            'name' => 'Dr. Grace Lindqvist',
            'specialty' => 'medicine',
            'role' => 'hospitalist',
            'npi' => '1700000011',
        ],
        [
            'name' => 'Dr. Omar Haddad',
            'specialty' => 'medicine',
            'role' => 'hospitalist',
            'npi' => '1700000012',
        ],
        [
            'name' => 'Dr. Beatrice Nwosu',
            'specialty' => 'adult_med_surg',
            'role' => 'attending',
            'npi' => '1700000013',
        ],
        [
            'name' => 'Dr. Leo Castellano',
            'specialty' => 'adult_med_surg',
            'role' => 'surgeon',
            'npi' => '1700000014',
        ],
        [
            'name' => 'Dr. Yuki Tanaka',
            'specialty' => 'oncology',
            'role' => 'attending',
            'npi' => '1700000015',
        ],
        [
            'name' => 'Dr. Samuel Ferreira',
            'specialty' => 'oncology',
            'role' => 'attending',
            'npi' => '1700000016',
        ],
        [
            'name' => 'Dr. Naomi Sjoberg',
            'specialty' => 'womens_health',
            'role' => 'attending',
            'npi' => '1700000017',
        ],
        [
            'name' => 'Dr. Carla Mendez',
            'specialty' => 'womens_health',
            'role' => 'surgeon',
            'npi' => '1700000018',
        ],
        [
            'name' => 'Dr. Patrick Donnelly',
            'specialty' => 'pediatrics',
            'role' => 'attending',
            'npi' => '1700000019',
        ],
        [
            'name' => 'Dr. Aisha Rahman',
            'specialty' => 'pediatrics',
            'role' => 'attending',
            'npi' => '1700000020',
        ],
        [
            'name' => 'Dr. Vivian Park',
            'specialty' => 'neonatology',
            'role' => 'attending',
            'npi' => '1700000021',
        ],
        [
            'name' => 'Dr. Howard Greenfield',
            'specialty' => 'behavioral_health',
            'role' => 'attending',
            'npi' => '1700000022',
        ],
        [
            'name' => 'Dr. Lucia Romano',
            'specialty' => 'rehabilitation',
            'role' => 'attending',
            'npi' => '1700000023',
        ],
        [
            'name' => 'Dr. Nathan Whitfield',
            'specialty' => 'emergency',
            'role' => 'attending',
            'npi' => '1700000024',
        ],
        [
            'name' => 'Dr. Farah Qureshi',
            'specialty' => 'emergency',
            'role' => 'attending',
            'npi' => '1700000025',
        ],
        [
            'name' => 'Dr. Gregory Holloway',
            'specialty' => 'emergency',
            'role' => 'attending',
            'npi' => '1700000026',
        ],
        [
            'name' => 'Dr. Ingrid Solberg',
            'specialty' => 'burn',
            'role' => 'surgeon',
            'npi' => '1700000027',
        ],
        [
            'name' => 'Dr. Maria Delacroix',
            'specialty' => 'perioperative',
            'role' => 'anesthesiologist',
            'npi' => '1700000028',
        ],
        [
            'name' => 'Dr. Kenji Watanabe',
            'specialty' => 'perioperative',
            'role' => 'anesthesiologist',
            'npi' => '1700000029',
        ],
        [
            'name' => 'Dr. Robert Aldridge',
            'specialty' => 'perioperative',
            'role' => 'anesthesiologist',
            'npi' => '1700000030',
        ],
    ],
    'nurses' => [
        [
            'name' => 'Maya Pendleton, RN',
            'role' => 'charge',
        ],
        [
            'name' => 'Devon Carlisle, RN',
            'role' => 'charge',
        ],
        [
            'name' => 'Imani Okafor, RN',
            'role' => 'charge',
        ],
        [
            'name' => 'Trevor Lindgren, RN',
            'role' => 'charge',
        ],
        [
            'name' => 'Rosa Iglesias, RN',
            'role' => 'staff',
        ],
        [
            'name' => 'Caleb Ferraro, RN',
            'role' => 'staff',
        ],
        [
            'name' => 'Hana Bashir, RN',
            'role' => 'staff',
        ],
        [
            'name' => 'Marcus Delgado, RN',
            'role' => 'staff',
        ],
        [
            'name' => 'Priscilla Vance, RN',
            'role' => 'staff',
        ],
        [
            'name' => 'Oliver Hawthorne, RN',
            'role' => 'staff',
        ],
        [
            'name' => 'Nadia Petrov, RN',
            'role' => 'staff',
        ],
        [
            'name' => 'Elijah Monroe, RN',
            'role' => 'staff',
        ],
        [
            'name' => 'Soledad Reyes, RN',
            'role' => 'staff',
        ],
        [
            'name' => 'Gavin Ashworth, RN',
            'role' => 'staff',
        ],
        [
            'name' => 'Talia Greenberg, RN',
            'role' => 'staff',
        ],
        [
            'name' => 'Dominic Russo, RN',
            'role' => 'staff',
        ],
        [
            'name' => 'Yvonne Mbeki, RN',
            'role' => 'staff',
        ],
        [
            'name' => 'Logan Pierce, RN',
            'role' => 'staff',
        ],
        [
            'name' => 'Anjali Kapoor, RN',
            'role' => 'staff',
        ],
        [
            'name' => 'Brendan Walsh, RN',
            'role' => 'staff',
        ],
        [
            'name' => 'Camille Fontaine, RN',
            'role' => 'staff',
        ],
        [
            'name' => 'Isaac Lindqvist, RN',
            'role' => 'staff',
        ],
        [
            'name' => 'Renata Salazar, RN',
            'role' => 'staff',
        ],
        [
            'name' => 'Aaron Whitcomb, RN',
            'role' => 'staff',
        ],
        [
            'name' => 'Lena Kowalski, RN',
            'role' => 'staff',
        ],
        [
            'name' => 'Damon Ferreira, RN',
            'role' => 'staff',
        ],
        [
            'name' => 'Sienna Abbott, RN',
            'role' => 'staff',
        ],
        [
            'name' => 'Malik Johnson-Reyes, RN',
            'role' => 'staff',
        ],
        [
            'name' => 'Greta Lindholm, RN',
            'role' => 'staff',
        ],
        [
            'name' => 'Theo Vasquez, RN',
            'role' => 'staff',
        ],
        [
            'name' => 'Joelle Marchetti, RN',
            'role' => 'staff',
        ],
        [
            'name' => 'Quentin Bowers, RN',
            'role' => 'staff',
        ],
        [
            'name' => 'Farida Nasser, RN',
            'role' => 'staff',
        ],
        [
            'name' => 'Cole Sandberg, RN',
            'role' => 'staff',
        ],
        [
            'name' => 'Marisol Cruz, RN',
            'role' => 'staff',
        ],
        [
            'name' => 'Wesley Trent, RN',
            'role' => 'staff',
        ],
    ],
    'care_teams' => [
        [
            'name' => 'Rapid Response Team',
            'code' => 'RRT',
        ],
        [
            'name' => 'Code Sepsis Team',
            'code' => 'SEPSIS',
        ],
        [
            'name' => 'Stroke Alert Team',
            'code' => 'STROKE',
        ],
        [
            'name' => 'STEMI / Cath Team',
            'code' => 'STEMI',
        ],
        [
            'name' => 'Trauma Activation Team',
            'code' => 'TRAUMA',
        ],
        [
            'name' => 'Heart Failure Team',
            'code' => 'CHF',
        ],
        [
            'name' => 'Palliative Care Consult',
            'code' => 'PALL',
        ],
        [
            'name' => 'Hospitalist Medicine Service',
            'code' => 'HOSP',
        ],
    ],
    'transport' => [
        'internal_team' => [
            'name' => 'Summit Patient Transport',
            'key' => 'patient_transport',
        ],
        'vendors' => [
            [
                'name' => 'Keystone Mobile Health (NEMT)',
                'key' => 'keystone_nemt',
                'type' => 'nemt',
            ],
            [
                'name' => 'Lehigh Valley Medical Transport',
                'key' => 'lvmt',
                'type' => 'ambulance',
            ],
        ],
    ],
    'post_acute_network' => [
        [
            'name' => 'Brookside Skilled Nursing & Rehabilitation',
            'type' => 'snf',
        ],
        [
            'name' => 'Cedar Run Sub-Acute Center',
            'type' => 'snf',
        ],
        [
            'name' => 'Summit Home Health Partners',
            'type' => 'home_health',
        ],
        [
            'name' => 'Keystone Hospice & Palliative Care',
            'type' => 'hospice',
        ],
        [
            'name' => 'Highlands Acute Rehabilitation Institute',
            'type' => 'inpatient_rehab',
        ],
    ],
    'ancillary_teams' => [
        [
            'name' => 'Physical / Occupational / Speech Therapy',
            'code' => 'PT_OT_SLP',
        ],
        [
            'name' => 'Social Work & Care Management',
            'code' => 'SW_CM',
        ],
        [
            'name' => 'Respiratory Therapy',
            'code' => 'RT',
        ],
        [
            'name' => 'Pharmacy',
            'code' => 'RX',
        ],
        [
            'name' => 'Imaging / Radiology',
            'code' => 'IMG',
        ],
        [
            'name' => 'Laboratory',
            'code' => 'LAB',
        ],
        [
            'name' => 'Environmental Services',
            'code' => 'EVS',
        ],
        [
            'name' => 'Nutrition Services',
            'code' => 'NUTR',
        ],
        [
            'name' => 'Case Management / Utilization Review',
            'code' => 'UR',
        ],
    ],
    'census_demo_targets' => [
        [
            'abbr' => 'MICU',
            'staffed_beds' => 24,
            'target_occupancy' => 0.92,
            'target_occupied' => 22,
        ],
        [
            'abbr' => 'SICU',
            'staffed_beds' => 24,
            'target_occupancy' => 0.85,
            'target_occupied' => 20,
        ],
        [
            'abbr' => 'NSICU',
            'staffed_beds' => 20,
            'target_occupancy' => 0.85,
            'target_occupied' => 17,
        ],
        [
            'abbr' => 'CVICU',
            'staffed_beds' => 20,
            'target_occupancy' => 0.9,
            'target_occupied' => 18,
        ],
        [
            'abbr' => 'BURN',
            'staffed_beds' => 8,
            'target_occupancy' => 0.85,
            'target_occupied' => 7,
        ],
        [
            'abbr' => 'BHU',
            'staffed_beds' => 24,
            'target_occupancy' => 0.85,
            'target_occupied' => 20,
        ],
        [
            'abbr' => '4W',
            'staffed_beds' => 28,
            'target_occupancy' => 0.85,
            'target_occupied' => 24,
        ],
        [
            'abbr' => '4E',
            'staffed_beds' => 28,
            'target_occupancy' => 0.85,
            'target_occupied' => 24,
        ],
        [
            'abbr' => '5W',
            'staffed_beds' => 28,
            'target_occupancy' => 0.85,
            'target_occupied' => 24,
        ],
        [
            'abbr' => '5E',
            'staffed_beds' => 28,
            'target_occupancy' => 0.88,
            'target_occupied' => 25,
        ],
        [
            'abbr' => '6W',
            'staffed_beds' => 24,
            'target_occupancy' => 0.85,
            'target_occupied' => 20,
        ],
        [
            'abbr' => '6E',
            'staffed_beds' => 24,
            'target_occupancy' => 0.91,
            'target_occupied' => 22,
        ],
        [
            'abbr' => '7E',
            'staffed_beds' => 32,
            'target_occupancy' => 0.85,
            'target_occupied' => 27,
        ],
        [
            'abbr' => '7W',
            'staffed_beds' => 32,
            'target_occupancy' => 0.85,
            'target_occupied' => 27,
        ],
        [
            'abbr' => 'ANT',
            'staffed_beds' => 12,
            'target_occupancy' => 0.85,
            'target_occupied' => 10,
        ],
        [
            'abbr' => 'PP',
            'staffed_beds' => 28,
            'target_occupancy' => 0.85,
            'target_occupied' => 24,
        ],
        [
            'abbr' => 'GYN',
            'staffed_beds' => 8,
            'target_occupancy' => 0.85,
            'target_occupied' => 7,
        ],
        [
            'abbr' => 'PED',
            'staffed_beds' => 24,
            'target_occupancy' => 0.85,
            'target_occupied' => 20,
        ],
        [
            'abbr' => 'PICU',
            'staffed_beds' => 12,
            'target_occupancy' => 0.85,
            'target_occupied' => 10,
        ],
        [
            'abbr' => 'NICU',
            'staffed_beds' => 12,
            'target_occupancy' => 0.85,
            'target_occupied' => 10,
        ],
        [
            'abbr' => 'ONC',
            'staffed_beds' => 24,
            'target_occupancy' => 0.93,
            'target_occupied' => 22,
        ],
        [
            'abbr' => 'BMT',
            'staffed_beds' => 16,
            'target_occupancy' => 0.94,
            'target_occupied' => 15,
        ],
        [
            'abbr' => 'AIR',
            'staffed_beds' => 20,
            'target_occupancy' => 0.85,
            'target_occupied' => 17,
        ],
        [
            'abbr' => 'ED',
            'staffed_beds' => 148,
            'target_occupancy' => 0.0,
            'target_occupied' => 0,
        ],
    ],
];
